services:
  - name: synaptic-cinema-backend
    env: python
    pythonVersion: "3.11"
    buildCommand: cd BACKEND && pip install -r requirements.txt
    startCommand: cd BACKEND && gunicorn app:app --bind :$PORT
